// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqrphuylyptqyhtazdam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxcnBodXlseXB0cXlodGF6ZGFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0Nzk3ODIsImV4cCI6MjA2ODA1NTc4Mn0.ozsCR1qCjyGzVwTk5aVWZJ11B79MTZdrSXxnvet6evY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});